apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rnd-data-team-edit
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: rnd-data-team
