apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rnd-data-team-view
  namespace: customer1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: rnd-data-team

