apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: data-pipeline
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
